// Ejercicio 100: funci√≥n normal que use throw para lanzar un error personalizado
function lanzarError(mensaje: string): never {
  throw new Error(mensaje);
}

// lanzarError("Este es un error personalizado");
